[scripts]  Add support for building and deploying on FreeBSD and OpenBSD.

diff --git a/scripts/z-run b/scripts/z-run
--- a/scripts/z-run
+++ b/scripts/z-run
@@ -16,22 +16,19 @@
 
 
 
-<< deploy / rsync / linux
-	test "${#}" -eq 1
-	_target="${1}"
-	shift -- 1
-	"${ZRUN[@]}" ':: deploy / release'
-	printf -- '[ii]  deploying to `%s`...\n' "${_target}" >&2
-	rsync -i -t -p --chmod=0555 -- ./.outputs/z-run--release--linux "${_target}"
-!!
-
-<< deploy / rsync / darwin
-	test "${#}" -eq 1
-	_target="${1}"
-	shift -- 1
-	"${ZRUN[@]}" ':: deploy / release'
-	printf -- '[ii]  deploying to `%s`...\n' "${_target}" >&2
-	rsync -i -t -p --chmod=0555 -- ./.outputs/z-run--release--darwin "${_target}"
+:: deploy / rsync / linux :: exec "${ZRUN[@]}" ':: deploy / rsync' linux "${@}"
+:: deploy / rsync / darwin :: exec "${ZRUN[@]}" ':: deploy / rsync' darwin "${@}"
+:: deploy / rsync / freebsd :: exec "${ZRUN[@]}" ':: deploy / rsync' freebsd "${@}"
+:: deploy / rsync / openbsd :: exec "${ZRUN[@]}" ':: deploy / rsync' openbsd "${@}"
+--<< deploy / rsync
+	test "${#}" -eq 2
+	_os="${1}"
+	_target="${2}"
+	shift -- 2
+	"${ZRUN[@]}" ':: deploy / release' "${_os}"
+	_source="./.outputs/z-run--release--${_os}"
+	printf -- '[ii]  deploying (`%s`) to `%s`...\n' "${_os}" "${_target}" >&2
+	rsync -i -t -p --chmod=0555 -- "${_source}" "${_target}"
 !!
 
 
@@ -53,12 +50,35 @@
 
 
 << deploy / release
+	if test "${#}" -ge 1 ; then
+		_os="${1}"
+		shift -- 1
+	else
+		_os='all'
+	fi
 	test "${#}" -eq 0
 	if test "${ZRUNDEV_NORELEASE:-}" == true ; then
 		exit -- 0
 	fi
-	"${ZRUN[@]}" ':: go / build / main / release / linux'
-	"${ZRUN[@]}" ':: go / build / main / release / darwin'
+	case "${_os}" in
+		( all | linux )
+			"${ZRUN[@]}" ':: go / build / main / release / linux'
+		;;&
+		( all | darwin )
+			"${ZRUN[@]}" ':: go / build / main / release / darwin'
+		;;&
+		( all | freebsd )
+			"${ZRUN[@]}" ':: go / build / main / release / freebsd'
+		;;&
+		( all | openbsd )
+			"${ZRUN[@]}" ':: go / build / main / release / openbsd'
+		;;&
+		( all | linux | darwin | freebsd | openbsd )
+		;;
+		( * )
+			printf -- '[ee]  invalid os `%s`;  aborting!\n' "${_os}" >&2
+		;;
+	esac
 !!
 
 
@@ -213,6 +233,16 @@
 
 << go / build / main / release / darwin
 	export -- GOOS=darwin
+	"${ZRUN[@]}" ':: go / build / main / release'
+!!
+
+<< go / build / main / release / freebsd
+	export -- GOOS=freebsd
+	"${ZRUN[@]}" ':: go / build / main / release'
+!!
+
+<< go / build / main / release / openbsd
+	export -- GOOS=openbsd
 	"${ZRUN[@]}" ':: go / build / main / release'
 !!
 
